name: PhotoNote
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
  SQLiteData:
    url: https://github.com/pointfreeco/sqlite-data
    majorVersion: 1.3.0
targets:
  PhotoNote:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - PhotoNote
    info:
      path: PhotoNote/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.PhotoNote"
  PhotoNoteTCA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - PhotoNoteTCA
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SQLiteData
        product: SQLiteData
        transitivelyLinkDependencies: true
    info:
      path: PhotoNoteTCA/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.PhotoNote"
      
