name: TCAField1
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
targets:
  TCAField1:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - TCAField1
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
    info:
      path: TCAField1/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.TCAField1"
  TCAField1Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: TCAField1Tests
    dependencies:
      - target: TCAField1
      
