name: HotProspects
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
  CodeScanner:
    url: https://github.com/twostraws/CodeScanner
    majorVersion: 2.5.2
  SQLiteData:
    url: https://github.com/pointfreeco/sqlite-data
    majorVersion: 1.3.0
targets:
  HotProspects:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - HotProspects
    dependencies:
      - package: CodeScanner
        product: CodeScanner
    info:
      path: HotProspects/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.HotProspects"
  HotProspectsTCA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HotProspectsTCA
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SQLiteData
        product: SQLiteData
    info:
      path: HotProspectsTCA/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.HotProspects"
