name: BucketList
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
  SQLiteData:
    url: https://github.com/pointfreeco/sqlite-data
    majorVersion: 1.3.0
targets:
  BucketList:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - BucketList
    info:
      path: BucketList/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.BucketList"
      TARGETED_DEVICE_FAMILY: "1"
  BucketListTCA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - BucketListTCA
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SQLiteData
        product: SQLiteData
    info:
      path: BucketListTCA/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.BucketList"
      TARGETED_DEVICE_FAMILY: "1"
    scheme:
      testTargets: [BucketListTCATests]
  BucketListTCATests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BucketListTCATests
    dependencies:
      - target: BucketListTCA
      
