name: Flashzilla
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
  SQLiteData:
    url: https://github.com/pointfreeco/sqlite-data
    majorVersion: 1.3.0
targets:
  Flashzilla:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Flashzilla
    info:
      path: Flashzilla/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.Flashzilla"
  FlashzillaTCA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - FlashzillaTCA
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SQLiteData
        product: SQLiteData
    info:
      path: FlashzillaTCA/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.FlashzillaTCA"
    scheme:
      testTargets: [FlashzillaTCATests]
  FlashzillaTCATests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FlashzillaTCATests
    dependencies:
      - target: FlashzillaTCA
      
