name: HabitTracking
options:
  bundleIdPrefix: me.jzj
settings:
  base:
    DEVELOPMENT_TEAM: "5WXVA53Q8X"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: Complete
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.23.1
targets:
  HabitTracking:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HabitTracking
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
    info:
      path: HabitTracking/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "me.jzj.HabitTracking"
      
